//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PW3Model", "FK__examen_re__id_al__3A4CA8FD", "alumno", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExamenServicio.alumno), "examen_realizado", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExamenServicio.examen_realizado))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PW3Model", "FK__curso__id_profes__2180FB33", "profesor", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExamenServicio.profesor), "curso", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExamenServicio.curso))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PW3Model", "FK__examen__id_curso__2BFE89A6", "curso", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExamenServicio.curso), "examen", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExamenServicio.examen))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PW3Model", "FK__examen_re__id_ex__3B40CD36", "examen", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExamenServicio.examen), "examen_realizado", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExamenServicio.examen_realizado))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PW3Model", "FK__pregunta__id_exa__30C33EC3", "examen", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExamenServicio.examen), "pregunta", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExamenServicio.pregunta))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PW3Model", "FK__respuesta__id_pr__3587F3E0", "pregunta", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExamenServicio.pregunta), "respuesta", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExamenServicio.respuesta))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PW3Model", "cursada", "alumno", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExamenServicio.alumno), "curso", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExamenServicio.curso))]

// Original file name:
// Generation date: 26/11/2013 03:11:59 p.m.
namespace ExamenServicio
{
    
    /// <summary>
    /// There are no comments for PW3Entities in the schema.
    /// </summary>
    public partial class PW3Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new PW3Entities object using the connection string found in the 'PW3Entities' section of the application configuration file.
        /// </summary>
        public PW3Entities() : 
                base("name=PW3Entities", "PW3Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PW3Entities object.
        /// </summary>
        public PW3Entities(string connectionString) : 
                base(connectionString, "PW3Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PW3Entities object.
        /// </summary>
        public PW3Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PW3Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for alumno in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<alumno> alumno
        {
            get
            {
                if ((this._alumno == null))
                {
                    this._alumno = base.CreateQuery<alumno>("[alumno]");
                }
                return this._alumno;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<alumno> _alumno;
        /// <summary>
        /// There are no comments for curso in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<curso> curso
        {
            get
            {
                if ((this._curso == null))
                {
                    this._curso = base.CreateQuery<curso>("[curso]");
                }
                return this._curso;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<curso> _curso;
        /// <summary>
        /// There are no comments for examen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<examen> examen
        {
            get
            {
                if ((this._examen == null))
                {
                    this._examen = base.CreateQuery<examen>("[examen]");
                }
                return this._examen;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<examen> _examen;
        /// <summary>
        /// There are no comments for examen_realizado in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<examen_realizado> examen_realizado
        {
            get
            {
                if ((this._examen_realizado == null))
                {
                    this._examen_realizado = base.CreateQuery<examen_realizado>("[examen_realizado]");
                }
                return this._examen_realizado;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<examen_realizado> _examen_realizado;
        /// <summary>
        /// There are no comments for pregunta in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<pregunta> pregunta
        {
            get
            {
                if ((this._pregunta == null))
                {
                    this._pregunta = base.CreateQuery<pregunta>("[pregunta]");
                }
                return this._pregunta;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<pregunta> _pregunta;
        /// <summary>
        /// There are no comments for profesor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<profesor> profesor
        {
            get
            {
                if ((this._profesor == null))
                {
                    this._profesor = base.CreateQuery<profesor>("[profesor]");
                }
                return this._profesor;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<profesor> _profesor;
        /// <summary>
        /// There are no comments for respuesta in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<respuesta> respuesta
        {
            get
            {
                if ((this._respuesta == null))
                {
                    this._respuesta = base.CreateQuery<respuesta>("[respuesta]");
                }
                return this._respuesta;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<respuesta> _respuesta;
        /// <summary>
        /// There are no comments for alumno in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToalumno(alumno alumno)
        {
            base.AddObject("alumno", alumno);
        }
        /// <summary>
        /// There are no comments for curso in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTocurso(curso curso)
        {
            base.AddObject("curso", curso);
        }
        /// <summary>
        /// There are no comments for examen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToexamen(examen examen)
        {
            base.AddObject("examen", examen);
        }
        /// <summary>
        /// There are no comments for examen_realizado in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToexamen_realizado(examen_realizado examen_realizado)
        {
            base.AddObject("examen_realizado", examen_realizado);
        }
        /// <summary>
        /// There are no comments for pregunta in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTopregunta(pregunta pregunta)
        {
            base.AddObject("pregunta", pregunta);
        }
        /// <summary>
        /// There are no comments for profesor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToprofesor(profesor profesor)
        {
            base.AddObject("profesor", profesor);
        }
        /// <summary>
        /// There are no comments for respuesta in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTorespuesta(respuesta respuesta)
        {
            base.AddObject("respuesta", respuesta);
        }
    }
    /// <summary>
    /// There are no comments for PW3Model.alumno in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_alumno
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="alumno")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class alumno : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new alumno object.
        /// </summary>
        /// <param name="id_alumno">Initial value of id_alumno.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static alumno Createalumno(int id_alumno)
        {
            alumno alumno = new alumno();
            alumno.id_alumno = id_alumno;
            return alumno;
        }
        /// <summary>
        /// There are no comments for property id_alumno in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_alumno
        {
            get
            {
                return this._id_alumno;
            }
            set
            {
                this.Onid_alumnoChanging(value);
                this.ReportPropertyChanging("id_alumno");
                this._id_alumno = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_alumno");
                this.Onid_alumnoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_alumno;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_alumnoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_alumnoChanged();
        /// <summary>
        /// There are no comments for property nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                this.OnnombreChanging(value);
                this.ReportPropertyChanging("nombre");
                this._nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("nombre");
                this.OnnombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanged();
        /// <summary>
        /// There are no comments for property apellido in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string apellido
        {
            get
            {
                return this._apellido;
            }
            set
            {
                this.OnapellidoChanging(value);
                this.ReportPropertyChanging("apellido");
                this._apellido = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("apellido");
                this.OnapellidoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _apellido;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnapellidoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnapellidoChanged();
        /// <summary>
        /// There are no comments for property mail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string mail
        {
            get
            {
                return this._mail;
            }
            set
            {
                this.OnmailChanging(value);
                this.ReportPropertyChanging("mail");
                this._mail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("mail");
                this.OnmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _mail;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmailChanged();
        /// <summary>
        /// There are no comments for property contraseña in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string contraseña
        {
            get
            {
                return this._contraseña;
            }
            set
            {
                this.OncontraseñaChanging(value);
                this.ReportPropertyChanging("contraseña");
                this._contraseña = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("contraseña");
                this.OncontraseñaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _contraseña;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncontraseñaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncontraseñaChanged();
        /// <summary>
        /// There are no comments for property dni in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string dni
        {
            get
            {
                return this._dni;
            }
            set
            {
                this.OndniChanging(value);
                this.ReportPropertyChanging("dni");
                this._dni = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("dni");
                this.OndniChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _dni;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndniChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndniChanged();
        /// <summary>
        /// There are no comments for examen_realizado in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__examen_re__id_al__3A4CA8FD", "examen_realizado")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<examen_realizado> examen_realizado
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<examen_realizado>("PW3Model.FK__examen_re__id_al__3A4CA8FD", "examen_realizado");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<examen_realizado>("PW3Model.FK__examen_re__id_al__3A4CA8FD", "examen_realizado", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for curso in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "cursada", "curso")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<curso> curso
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<curso>("PW3Model.cursada", "curso");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<curso>("PW3Model.cursada", "curso", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PW3Model.curso in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_curso
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="curso")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class curso : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new curso object.
        /// </summary>
        /// <param name="id_curso">Initial value of id_curso.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static curso Createcurso(int id_curso)
        {
            curso curso = new curso();
            curso.id_curso = id_curso;
            return curso;
        }
        /// <summary>
        /// There are no comments for property id_curso in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_curso
        {
            get
            {
                return this._id_curso;
            }
            set
            {
                this.Onid_cursoChanging(value);
                this.ReportPropertyChanging("id_curso");
                this._id_curso = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_curso");
                this.Onid_cursoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_curso;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_cursoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_cursoChanged();
        /// <summary>
        /// There are no comments for property nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                this.OnnombreChanging(value);
                this.ReportPropertyChanging("nombre");
                this._nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("nombre");
                this.OnnombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanged();
        /// <summary>
        /// There are no comments for property fecha_inicio in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> fecha_inicio
        {
            get
            {
                return this._fecha_inicio;
            }
            set
            {
                this.Onfecha_inicioChanging(value);
                this.ReportPropertyChanging("fecha_inicio");
                this._fecha_inicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_inicio");
                this.Onfecha_inicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _fecha_inicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_inicioChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_inicioChanged();
        /// <summary>
        /// There are no comments for property fecha_fin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> fecha_fin
        {
            get
            {
                return this._fecha_fin;
            }
            set
            {
                this.Onfecha_finChanging(value);
                this.ReportPropertyChanging("fecha_fin");
                this._fecha_fin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_fin");
                this.Onfecha_finChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _fecha_fin;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_finChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_finChanged();
        /// <summary>
        /// There are no comments for profesor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__curso__id_profes__2180FB33", "profesor")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public profesor profesor
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<profesor>("PW3Model.FK__curso__id_profes__2180FB33", "profesor").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<profesor>("PW3Model.FK__curso__id_profes__2180FB33", "profesor").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for profesor in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<profesor> profesorReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<profesor>("PW3Model.FK__curso__id_profes__2180FB33", "profesor");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<profesor>("PW3Model.FK__curso__id_profes__2180FB33", "profesor", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for examen in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__examen__id_curso__2BFE89A6", "examen")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<examen> examen
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<examen>("PW3Model.FK__examen__id_curso__2BFE89A6", "examen");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<examen>("PW3Model.FK__examen__id_curso__2BFE89A6", "examen", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for alumno in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "cursada", "alumno")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<alumno> alumno
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<alumno>("PW3Model.cursada", "alumno");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<alumno>("PW3Model.cursada", "alumno", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PW3Model.examen in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_examen
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="examen")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class examen : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new examen object.
        /// </summary>
        /// <param name="id_examen">Initial value of id_examen.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static examen Createexamen(int id_examen)
        {
            examen examen = new examen();
            examen.id_examen = id_examen;
            return examen;
        }
        /// <summary>
        /// There are no comments for property id_examen in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_examen
        {
            get
            {
                return this._id_examen;
            }
            set
            {
                this.Onid_examenChanging(value);
                this.ReportPropertyChanging("id_examen");
                this._id_examen = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_examen");
                this.Onid_examenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_examen;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_examenChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_examenChanged();
        /// <summary>
        /// There are no comments for property nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                this.OnnombreChanging(value);
                this.ReportPropertyChanging("nombre");
                this._nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("nombre");
                this.OnnombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanged();
        /// <summary>
        /// There are no comments for property descripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string descripcion
        {
            get
            {
                return this._descripcion;
            }
            set
            {
                this.OndescripcionChanging(value);
                this.ReportPropertyChanging("descripcion");
                this._descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("descripcion");
                this.OndescripcionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _descripcion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescripcionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescripcionChanged();
        /// <summary>
        /// There are no comments for property porc_aprobacion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> porc_aprobacion
        {
            get
            {
                return this._porc_aprobacion;
            }
            set
            {
                this.Onporc_aprobacionChanging(value);
                this.ReportPropertyChanging("porc_aprobacion");
                this._porc_aprobacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("porc_aprobacion");
                this.Onporc_aprobacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _porc_aprobacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onporc_aprobacionChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onporc_aprobacionChanged();
        /// <summary>
        /// There are no comments for property duracion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> duracion
        {
            get
            {
                return this._duracion;
            }
            set
            {
                this.OnduracionChanging(value);
                this.ReportPropertyChanging("duracion");
                this._duracion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("duracion");
                this.OnduracionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _duracion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnduracionChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnduracionChanged();
        /// <summary>
        /// There are no comments for property fecha_tope in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> fecha_tope
        {
            get
            {
                return this._fecha_tope;
            }
            set
            {
                this.Onfecha_topeChanging(value);
                this.ReportPropertyChanging("fecha_tope");
                this._fecha_tope = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_tope");
                this.Onfecha_topeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _fecha_tope;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_topeChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_topeChanged();
        /// <summary>
        /// There are no comments for curso in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__examen__id_curso__2BFE89A6", "curso")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public curso curso
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<curso>("PW3Model.FK__examen__id_curso__2BFE89A6", "curso").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<curso>("PW3Model.FK__examen__id_curso__2BFE89A6", "curso").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for curso in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<curso> cursoReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<curso>("PW3Model.FK__examen__id_curso__2BFE89A6", "curso");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<curso>("PW3Model.FK__examen__id_curso__2BFE89A6", "curso", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for examen_realizado in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__examen_re__id_ex__3B40CD36", "examen_realizado")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<examen_realizado> examen_realizado
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<examen_realizado>("PW3Model.FK__examen_re__id_ex__3B40CD36", "examen_realizado");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<examen_realizado>("PW3Model.FK__examen_re__id_ex__3B40CD36", "examen_realizado", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for pregunta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__pregunta__id_exa__30C33EC3", "pregunta")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<pregunta> pregunta
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<pregunta>("PW3Model.FK__pregunta__id_exa__30C33EC3", "pregunta");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<pregunta>("PW3Model.FK__pregunta__id_exa__30C33EC3", "pregunta", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PW3Model.examen_realizado in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_alumno
    /// id_examen
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="examen_realizado")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class examen_realizado : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new examen_realizado object.
        /// </summary>
        /// <param name="id_alumno">Initial value of id_alumno.</param>
        /// <param name="id_examen">Initial value of id_examen.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static examen_realizado Createexamen_realizado(int id_alumno, int id_examen)
        {
            examen_realizado examen_realizado = new examen_realizado();
            examen_realizado.id_alumno = id_alumno;
            examen_realizado.id_examen = id_examen;
            return examen_realizado;
        }
        /// <summary>
        /// There are no comments for property id_alumno in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_alumno
        {
            get
            {
                return this._id_alumno;
            }
            set
            {
                this.Onid_alumnoChanging(value);
                this.ReportPropertyChanging("id_alumno");
                this._id_alumno = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_alumno");
                this.Onid_alumnoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_alumno;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_alumnoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_alumnoChanged();
        /// <summary>
        /// There are no comments for property id_examen in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_examen
        {
            get
            {
                return this._id_examen;
            }
            set
            {
                this.Onid_examenChanging(value);
                this.ReportPropertyChanging("id_examen");
                this._id_examen = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_examen");
                this.Onid_examenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_examen;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_examenChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_examenChanged();
        /// <summary>
        /// There are no comments for property estado in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string estado
        {
            get
            {
                return this._estado;
            }
            set
            {
                this.OnestadoChanging(value);
                this.ReportPropertyChanging("estado");
                this._estado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("estado");
                this.OnestadoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _estado;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnestadoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnestadoChanged();
        /// <summary>
        /// There are no comments for property resultado in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> resultado
        {
            get
            {
                return this._resultado;
            }
            set
            {
                this.OnresultadoChanging(value);
                this.ReportPropertyChanging("resultado");
                this._resultado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("resultado");
                this.OnresultadoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _resultado;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnresultadoChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnresultadoChanged();
        /// <summary>
        /// There are no comments for alumno in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__examen_re__id_al__3A4CA8FD", "alumno")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public alumno alumno
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<alumno>("PW3Model.FK__examen_re__id_al__3A4CA8FD", "alumno").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<alumno>("PW3Model.FK__examen_re__id_al__3A4CA8FD", "alumno").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for alumno in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<alumno> alumnoReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<alumno>("PW3Model.FK__examen_re__id_al__3A4CA8FD", "alumno");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<alumno>("PW3Model.FK__examen_re__id_al__3A4CA8FD", "alumno", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for examen in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__examen_re__id_ex__3B40CD36", "examen")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public examen examen
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<examen>("PW3Model.FK__examen_re__id_ex__3B40CD36", "examen").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<examen>("PW3Model.FK__examen_re__id_ex__3B40CD36", "examen").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for examen in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<examen> examenReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<examen>("PW3Model.FK__examen_re__id_ex__3B40CD36", "examen");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<examen>("PW3Model.FK__examen_re__id_ex__3B40CD36", "examen", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PW3Model.pregunta in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_pregunta
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="pregunta")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class pregunta : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new pregunta object.
        /// </summary>
        /// <param name="id_pregunta">Initial value of id_pregunta.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static pregunta Createpregunta(int id_pregunta)
        {
            pregunta pregunta = new pregunta();
            pregunta.id_pregunta = id_pregunta;
            return pregunta;
        }
        /// <summary>
        /// There are no comments for property id_pregunta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_pregunta
        {
            get
            {
                return this._id_pregunta;
            }
            set
            {
                this.Onid_preguntaChanging(value);
                this.ReportPropertyChanging("id_pregunta");
                this._id_pregunta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_pregunta");
                this.Onid_preguntaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_pregunta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_preguntaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_preguntaChanged();
        /// <summary>
        /// There are no comments for property descripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string descripcion
        {
            get
            {
                return this._descripcion;
            }
            set
            {
                this.OndescripcionChanging(value);
                this.ReportPropertyChanging("descripcion");
                this._descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("descripcion");
                this.OndescripcionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _descripcion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescripcionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescripcionChanged();
        /// <summary>
        /// There are no comments for examen in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__pregunta__id_exa__30C33EC3", "examen")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public examen examen
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<examen>("PW3Model.FK__pregunta__id_exa__30C33EC3", "examen").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<examen>("PW3Model.FK__pregunta__id_exa__30C33EC3", "examen").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for examen in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<examen> examenReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<examen>("PW3Model.FK__pregunta__id_exa__30C33EC3", "examen");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<examen>("PW3Model.FK__pregunta__id_exa__30C33EC3", "examen", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for respuesta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__respuesta__id_pr__3587F3E0", "respuesta")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<respuesta> respuesta
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<respuesta>("PW3Model.FK__respuesta__id_pr__3587F3E0", "respuesta");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<respuesta>("PW3Model.FK__respuesta__id_pr__3587F3E0", "respuesta", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PW3Model.profesor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_profesor
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="profesor")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class profesor : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new profesor object.
        /// </summary>
        /// <param name="id_profesor">Initial value of id_profesor.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static profesor Createprofesor(int id_profesor)
        {
            profesor profesor = new profesor();
            profesor.id_profesor = id_profesor;
            return profesor;
        }
        /// <summary>
        /// There are no comments for property id_profesor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_profesor
        {
            get
            {
                return this._id_profesor;
            }
            set
            {
                this.Onid_profesorChanging(value);
                this.ReportPropertyChanging("id_profesor");
                this._id_profesor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_profesor");
                this.Onid_profesorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_profesor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_profesorChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_profesorChanged();
        /// <summary>
        /// There are no comments for property nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                this.OnnombreChanging(value);
                this.ReportPropertyChanging("nombre");
                this._nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("nombre");
                this.OnnombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreChanged();
        /// <summary>
        /// There are no comments for property apellido in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string apellido
        {
            get
            {
                return this._apellido;
            }
            set
            {
                this.OnapellidoChanging(value);
                this.ReportPropertyChanging("apellido");
                this._apellido = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("apellido");
                this.OnapellidoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _apellido;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnapellidoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnapellidoChanged();
        /// <summary>
        /// There are no comments for property mail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string mail
        {
            get
            {
                return this._mail;
            }
            set
            {
                this.OnmailChanging(value);
                this.ReportPropertyChanging("mail");
                this._mail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("mail");
                this.OnmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _mail;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmailChanged();
        /// <summary>
        /// There are no comments for property contraseña in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string contraseña
        {
            get
            {
                return this._contraseña;
            }
            set
            {
                this.OncontraseñaChanging(value);
                this.ReportPropertyChanging("contraseña");
                this._contraseña = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("contraseña");
                this.OncontraseñaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _contraseña;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncontraseñaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncontraseñaChanged();
        /// <summary>
        /// There are no comments for curso in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__curso__id_profes__2180FB33", "curso")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<curso> curso
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<curso>("PW3Model.FK__curso__id_profes__2180FB33", "curso");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<curso>("PW3Model.FK__curso__id_profes__2180FB33", "curso", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PW3Model.respuesta in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_respuesta
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="respuesta")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class respuesta : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new respuesta object.
        /// </summary>
        /// <param name="id_respuesta">Initial value of id_respuesta.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static respuesta Createrespuesta(int id_respuesta)
        {
            respuesta respuesta = new respuesta();
            respuesta.id_respuesta = id_respuesta;
            return respuesta;
        }
        /// <summary>
        /// There are no comments for property id_respuesta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_respuesta
        {
            get
            {
                return this._id_respuesta;
            }
            set
            {
                this.Onid_respuestaChanging(value);
                this.ReportPropertyChanging("id_respuesta");
                this._id_respuesta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_respuesta");
                this.Onid_respuestaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_respuesta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_respuestaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_respuestaChanged();
        /// <summary>
        /// There are no comments for property descripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string descripcion
        {
            get
            {
                return this._descripcion;
            }
            set
            {
                this.OndescripcionChanging(value);
                this.ReportPropertyChanging("descripcion");
                this._descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("descripcion");
                this.OndescripcionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _descripcion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescripcionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescripcionChanged();
        /// <summary>
        /// There are no comments for property correcta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string correcta
        {
            get
            {
                return this._correcta;
            }
            set
            {
                this.OncorrectaChanging(value);
                this.ReportPropertyChanging("correcta");
                this._correcta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("correcta");
                this.OncorrectaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _correcta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncorrectaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncorrectaChanged();
        /// <summary>
        /// There are no comments for pregunta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__respuesta__id_pr__3587F3E0", "pregunta")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public pregunta pregunta
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<pregunta>("PW3Model.FK__respuesta__id_pr__3587F3E0", "pregunta").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<pregunta>("PW3Model.FK__respuesta__id_pr__3587F3E0", "pregunta").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for pregunta in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<pregunta> preguntaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<pregunta>("PW3Model.FK__respuesta__id_pr__3587F3E0", "pregunta");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<pregunta>("PW3Model.FK__respuesta__id_pr__3587F3E0", "pregunta", value);
                }
            }
        }
    }
}
