//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PW3Model", "FK__curso__id_profes__08EA5793", "profesor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.Entity.profesor), "curso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.Entity.curso), true)]
[assembly: EdmRelationshipAttribute("PW3Model", "cursada", "alumno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.Entity.alumno), "curso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.Entity.curso))]

#endregion

namespace WebApplication1.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PW3Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PW3Entities object using the connection string found in the 'PW3Entities' section of the application configuration file.
        /// </summary>
        public PW3Entities() : base("name=PW3Entities", "PW3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PW3Entities object.
        /// </summary>
        public PW3Entities(string connectionString) : base(connectionString, "PW3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PW3Entities object.
        /// </summary>
        public PW3Entities(EntityConnection connection) : base(connection, "PW3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<alumno> alumno
        {
            get
            {
                if ((_alumno == null))
                {
                    _alumno = base.CreateObjectSet<alumno>("alumno");
                }
                return _alumno;
            }
        }
        private ObjectSet<alumno> _alumno;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<curso> curso
        {
            get
            {
                if ((_curso == null))
                {
                    _curso = base.CreateObjectSet<curso>("curso");
                }
                return _curso;
            }
        }
        private ObjectSet<curso> _curso;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<profesor> profesor
        {
            get
            {
                if ((_profesor == null))
                {
                    _profesor = base.CreateObjectSet<profesor>("profesor");
                }
                return _profesor;
            }
        }
        private ObjectSet<profesor> _profesor;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the alumno EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToalumno(alumno alumno)
        {
            base.AddObject("alumno", alumno);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the curso EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocurso(curso curso)
        {
            base.AddObject("curso", curso);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the profesor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprofesor(profesor profesor)
        {
            base.AddObject("profesor", profesor);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="alumno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class alumno : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new alumno object.
        /// </summary>
        /// <param name="id_alumno">Initial value of the id_alumno property.</param>
        public static alumno Createalumno(global::System.Int32 id_alumno)
        {
            alumno alumno = new alumno();
            alumno.id_alumno = id_alumno;
            return alumno;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alumno
        {
            get
            {
                return _id_alumno;
            }
            set
            {
                if (_id_alumno != value)
                {
                    Onid_alumnoChanging(value);
                    ReportPropertyChanging("id_alumno");
                    _id_alumno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_alumno");
                    Onid_alumnoChanged();
                }
            }
        }
        private global::System.Int32 _id_alumno;
        partial void Onid_alumnoChanging(global::System.Int32 value);
        partial void Onid_alumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mail
        {
            get
            {
                return _mail;
            }
            set
            {
                OnmailChanging(value);
                ReportPropertyChanging("mail");
                _mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mail");
                OnmailChanged();
            }
        }
        private global::System.String _mail;
        partial void OnmailChanging(global::System.String value);
        partial void OnmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contraseña
        {
            get
            {
                return _contraseña;
            }
            set
            {
                OncontraseñaChanging(value);
                ReportPropertyChanging("contraseña");
                _contraseña = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contraseña");
                OncontraseñaChanged();
            }
        }
        private global::System.String _contraseña;
        partial void OncontraseñaChanging(global::System.String value);
        partial void OncontraseñaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3Model", "cursada", "curso")]
        public EntityCollection<curso> curso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<curso>("PW3Model.cursada", "curso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<curso>("PW3Model.cursada", "curso", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="curso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class curso : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new curso object.
        /// </summary>
        /// <param name="id_curso">Initial value of the id_curso property.</param>
        public static curso Createcurso(global::System.Int32 id_curso)
        {
            curso curso = new curso();
            curso.id_curso = id_curso;
            return curso;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_curso
        {
            get
            {
                return _id_curso;
            }
            set
            {
                if (_id_curso != value)
                {
                    Onid_cursoChanging(value);
                    ReportPropertyChanging("id_curso");
                    _id_curso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_curso");
                    Onid_cursoChanged();
                }
            }
        }
        private global::System.Int32 _id_curso;
        partial void Onid_cursoChanging(global::System.Int32 value);
        partial void Onid_cursoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_inicio
        {
            get
            {
                return _fecha_inicio;
            }
            set
            {
                Onfecha_inicioChanging(value);
                ReportPropertyChanging("fecha_inicio");
                _fecha_inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_inicio");
                Onfecha_inicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_inicio;
        partial void Onfecha_inicioChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_inicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_fin
        {
            get
            {
                return _fecha_fin;
            }
            set
            {
                Onfecha_finChanging(value);
                ReportPropertyChanging("fecha_fin");
                _fecha_fin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_fin");
                Onfecha_finChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_fin;
        partial void Onfecha_finChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_finChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_profesor
        {
            get
            {
                return _id_profesor;
            }
            set
            {
                Onid_profesorChanging(value);
                ReportPropertyChanging("id_profesor");
                _id_profesor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_profesor");
                Onid_profesorChanged();
            }
        }
        private Nullable<global::System.Int32> _id_profesor;
        partial void Onid_profesorChanging(Nullable<global::System.Int32> value);
        partial void Onid_profesorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__curso__id_profes__08EA5793", "profesor")]
        public profesor profesor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<profesor>("PW3Model.FK__curso__id_profes__08EA5793", "profesor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<profesor>("PW3Model.FK__curso__id_profes__08EA5793", "profesor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<profesor> profesorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<profesor>("PW3Model.FK__curso__id_profes__08EA5793", "profesor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<profesor>("PW3Model.FK__curso__id_profes__08EA5793", "profesor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3Model", "cursada", "alumno")]
        public EntityCollection<alumno> alumno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<alumno>("PW3Model.cursada", "alumno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<alumno>("PW3Model.cursada", "alumno", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3Model", Name="profesor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class profesor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new profesor object.
        /// </summary>
        /// <param name="id_profesor">Initial value of the id_profesor property.</param>
        public static profesor Createprofesor(global::System.Int32 id_profesor)
        {
            profesor profesor = new profesor();
            profesor.id_profesor = id_profesor;
            return profesor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_profesor
        {
            get
            {
                return _id_profesor;
            }
            set
            {
                if (_id_profesor != value)
                {
                    Onid_profesorChanging(value);
                    ReportPropertyChanging("id_profesor");
                    _id_profesor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_profesor");
                    Onid_profesorChanged();
                }
            }
        }
        private global::System.Int32 _id_profesor;
        partial void Onid_profesorChanging(global::System.Int32 value);
        partial void Onid_profesorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mail
        {
            get
            {
                return _mail;
            }
            set
            {
                OnmailChanging(value);
                ReportPropertyChanging("mail");
                _mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mail");
                OnmailChanged();
            }
        }
        private global::System.String _mail;
        partial void OnmailChanging(global::System.String value);
        partial void OnmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contraseña
        {
            get
            {
                return _contraseña;
            }
            set
            {
                OncontraseñaChanging(value);
                ReportPropertyChanging("contraseña");
                _contraseña = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contraseña");
                OncontraseñaChanged();
            }
        }
        private global::System.String _contraseña;
        partial void OncontraseñaChanging(global::System.String value);
        partial void OncontraseñaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3Model", "FK__curso__id_profes__08EA5793", "curso")]
        public EntityCollection<curso> curso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<curso>("PW3Model.FK__curso__id_profes__08EA5793", "curso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<curso>("PW3Model.FK__curso__id_profes__08EA5793", "curso", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
